# Generated by Django 4.2.21 on 2025-05-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(db_index=True, default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Order',
                'verbose_name_plural': 'Amazon Orders',
            },
        ),
        migrations.CreateModel(
            name='FirstcryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(db_index=True, default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'FirstCry Order',
                'verbose_name_plural': 'FirstCry Orders',
            },
        ),
        migrations.CreateModel(
            name='FlipkarOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(db_index=True, default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Flipkart Order',
                'verbose_name_plural': 'Flipkart Orders',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MeeshoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(db_index=True, default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Meesho Order',
                'verbose_name_plural': 'Meesho Orders',
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist_id', models.CharField(max_length=10, unique=True)),
                ('picklist_type', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multi')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PRINTED', 'Printed'), ('PACKING', 'Packing'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10)),
                ('platform', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PicklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('picked', models.BooleanField(default=False)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordercycle.picklist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('label_printer_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('default_print_settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='PicklistItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('picked', models.BooleanField(default=False)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to='ordercycle.picker')),
                ('picklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='ordercycle.picklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='PicklistDispatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('dispatched_orders', models.IntegerField(default=0)),
                ('complete_orders', models.IntegerField(default=0)),
                ('total_relevant_orders', models.IntegerField(default=0)),
                ('is_fully_dispatched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('picklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_status', to='ordercycle.picklist')),
            ],
            options={
                'verbose_name': 'Picklist Dispatch Status',
                'verbose_name_plural': 'Picklist Dispatch Statuses',
            },
        ),
        migrations.CreateModel(
            name='OrderPDF',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pdf_content', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(default='unknown', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='ordercycle__created_92c173_idx')],
            },
        ),
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('box_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_check', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='ordercycle__sku_d5e500_idx'), models.Index(fields=['location'], name='ordercycle__locatio_493808_idx'), models.Index(fields=['product_id'], name='ordercycle__product_817d78_idx')],
                'unique_together': {('sku', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PicklistSKUValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_validations', to='ordercycle.picklist')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['picklist', 'sku'], name='ordercycle__picklis_50a739_idx'), models.Index(fields=['picklist', 'validated'], name='ordercycle__picklis_7f11d1_idx'), models.Index(fields=['order_number', 'validated'], name='ordercycle__order_n_ffb6d4_idx')],
                'unique_together': {('picklist', 'sku', 'order_number')},
            },
        ),
    ]
