# Generated by Django 5.1.6 on 2025-04-18 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FirstcryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlipkarOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist_id', models.CharField(max_length=10, unique=True)),
                ('picklist_type', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multi')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PRINTED', 'Printed'), ('PACKING', 'Packing'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10)),
                ('platform', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('box_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_check', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='ordercycle__sku_d5e500_idx'), models.Index(fields=['location'], name='ordercycle__locatio_493808_idx'), models.Index(fields=['product_id'], name='ordercycle__product_817d78_idx')],
                'unique_together': {('sku', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PicklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('picked', models.BooleanField(default=False)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordercycle.picklist')),
            ],
        ),
        migrations.CreateModel(
            name='PicklistItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('picked', models.BooleanField(default=False)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to='ordercycle.picker')),
                ('picklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='ordercycle.picklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('label_printer_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('default_print_settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
