# Generated by Django 4.2.21 on 2025-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistskuvalidation',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='picklistskuvalidation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picklistskuvalidation',
            name='validated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='picklistskuvalidation',
            index=models.Index(fields=['validated_count', 'quantity'], name='ordercycle__validat_dbcc7f_idx'),
        ),
    ]
