# Generated by Django 4.2.25 on 2025-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='table',
            field=models.CharField(blank=True, choices=[('1', 'Table 1'), ('2', 'Table 2'), ('3', 'Table 3'), ('4', 'Table 4'), ('5', 'Table 5'), ('6', 'Table 6')], max_length=10, null=True),
        ),
    ]
