# Generated by Django 5.1.6 on 2025-04-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeeshoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='Single', max_length=200)),
                ('status', models.CharField(default='Ready to Process', max_length=200)),
                ('pdf_url', models.CharField(max_length=300)),
                ('AWB', models.CharField(max_length=100)),
            ],
        ),
    ]
