# Generated by Django 4.2.21 on 2025-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordercycle", "0002_picklistskuvalidation_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonorders",
            name="is_printed",
            field=models.BooleanField(
                default=False, help_text="Whether the order has been printed"
            ),
        ),
        migrations.AddField(
            model_name="amazonorders",
            name="is_validated",
            field=models.BooleanField(
                default=False, help_text="Whether AWB has been validated"
            ),
        ),
        migrations.AddField(
            model_name="amazonorders",
            name="printed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was printed", null=True
            ),
        ),
        migrations.AddField(
            model_name="amazonorders",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was marked as processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="amazonorders",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When AWB was validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="firstcryorders",
            name="is_printed",
            field=models.BooleanField(
                default=False, help_text="Whether the order has been printed"
            ),
        ),
        migrations.AddField(
            model_name="firstcryorders",
            name="is_validated",
            field=models.BooleanField(
                default=False, help_text="Whether AWB has been validated"
            ),
        ),
        migrations.AddField(
            model_name="firstcryorders",
            name="printed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was printed", null=True
            ),
        ),
        migrations.AddField(
            model_name="firstcryorders",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was marked as processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="firstcryorders",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When AWB was validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="flipkarorders",
            name="is_printed",
            field=models.BooleanField(
                default=False, help_text="Whether the order has been printed"
            ),
        ),
        migrations.AddField(
            model_name="flipkarorders",
            name="is_validated",
            field=models.BooleanField(
                default=False, help_text="Whether AWB has been validated"
            ),
        ),
        migrations.AddField(
            model_name="flipkarorders",
            name="printed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was printed", null=True
            ),
        ),
        migrations.AddField(
            model_name="flipkarorders",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was marked as processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="flipkarorders",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When AWB was validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeshoorders",
            name="is_printed",
            field=models.BooleanField(
                default=False, help_text="Whether the order has been printed"
            ),
        ),
        migrations.AddField(
            model_name="meeshoorders",
            name="is_validated",
            field=models.BooleanField(
                default=False, help_text="Whether AWB has been validated"
            ),
        ),
        migrations.AddField(
            model_name="meeshoorders",
            name="printed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was printed", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeshoorders",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was marked as processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeshoorders",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When AWB was validated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="picklist",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PRINTED", "Printed"),
                    ("PACKING", "Packing"),
                    ("PARTIAL_DISPATCH", "Partial Dispatch"),
                    ("DISPATCH", "Dispatch"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
