# Generated by Django 5.2 on 2025-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0002_meeshoorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonorders',
            options={'verbose_name': 'Amazon Order', 'verbose_name_plural': 'Amazon Orders'},
        ),
        migrations.AlterModelOptions(
            name='firstcryorders',
            options={'verbose_name': 'FirstCry Order', 'verbose_name_plural': 'FirstCry Orders'},
        ),
        migrations.AlterModelOptions(
            name='flipkarorders',
            options={'verbose_name': 'Flipkart Order', 'verbose_name_plural': 'Flipkart Orders'},
        ),
        migrations.AlterModelOptions(
            name='meeshoorders',
            options={'verbose_name': 'Meesho Order', 'verbose_name_plural': 'Meesho Orders'},
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='AWB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='order_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='sku',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='status',
            field=models.CharField(db_index=True, default='Ready to Process', max_length=200),
        ),
        migrations.AlterField(
            model_name='firstcryorders',
            name='AWB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firstcryorders',
            name='order_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='firstcryorders',
            name='sku',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='firstcryorders',
            name='status',
            field=models.CharField(db_index=True, default='Ready to Process', max_length=200),
        ),
        migrations.AlterField(
            model_name='flipkarorders',
            name='AWB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flipkarorders',
            name='order_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flipkarorders',
            name='sku',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flipkarorders',
            name='status',
            field=models.CharField(db_index=True, default='Ready to Process', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeshoorders',
            name='AWB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeshoorders',
            name='order_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meeshoorders',
            name='sku',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meeshoorders',
            name='status',
            field=models.CharField(db_index=True, default='Ready to Process', max_length=200),
        ),
    ]
