# Generated by Django 5.2 on 2025-05-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0003_alter_amazonorders_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicklistDispatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('dispatched_orders', models.IntegerField(default=0)),
                ('is_fully_dispatched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('picklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_status', to='ordercycle.picklist')),
            ],
            options={
                'verbose_name': 'Picklist Dispatch Status',
                'verbose_name_plural': 'Picklist Dispatch Statuses',
            },
        ),
    ]
