# Generated by Django 4.2.25 on 2025-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0003_amazonorders_is_printed_amazonorders_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpdf',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order PDF', 'verbose_name_plural': 'Order PDFs'},
        ),
        migrations.RemoveIndex(
            model_name='orderpdf',
            name='ordercycle__created_92c173_idx',
        ),
        migrations.RemoveField(
            model_name='orderpdf',
            name='pdf_content',
        ),
        migrations.AddField(
            model_name='orderpdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='order_pdfs/'),
        ),
        migrations.AddField(
            model_name='orderpdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderpdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderpdf',
            name='order_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderpdf',
            name='source_type',
            field=models.CharField(default='upload', max_length=50),
        ),
    ]
