# Generated by Django 5.2 on 2025-05-14 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0004_picklistdispatchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
