# Generated by Django 5.2 on 2025-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPDF',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pdf_content', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(default='unknown', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddIndex(
            model_name='orderpdf',
            index=models.Index(fields=['created_at'], name='ordercycle__created_92c173_idx'),
        ),
    ]
