# Generated by Django 4.2.21 on 2025-05-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordercycle', '0007_orderpdf_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicklistSKUValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('order_number', models.CharField(db_index=True, max_length=200)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_validations', to='ordercycle.picklist')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['picklist', 'sku'], name='ordercycle__picklis_50a739_idx'), models.Index(fields=['picklist', 'validated'], name='ordercycle__picklis_7f11d1_idx'), models.Index(fields=['order_number', 'validated'], name='ordercycle__order_n_ffb6d4_idx')],
                'unique_together': {('picklist', 'sku', 'order_number')},
            },
        ),
    ]
