# Generated by Django 4.2.21 on 2025-05-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0008_picklistskuvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistdispatchstatus',
            name='complete_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picklistdispatchstatus',
            name='total_relevant_orders',
            field=models.IntegerField(default=0),
        ),
    ]
