# Generated by Django 4.2.21 on 2025-05-28 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordercycle', '0010_add_quantity_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='picklistskuvalidation',
            name='ordercycle__picklis_50a739_idx',
        ),
        migrations.RemoveIndex(
            model_name='picklistskuvalidation',
            name='ordercycle__picklis_7f11d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='picklistskuvalidation',
            name='ordercycle__order_n_ffb6d4_idx',
        ),
        migrations.RemoveField(
            model_name='picklistskuvalidation',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='picklistskuvalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picklistskuvalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='picklistskuvalidation',
            name='order_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picklistskuvalidation',
            name='picklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordercycle.picklist'),
        ),
        migrations.AlterField(
            model_name='picklistskuvalidation',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='picklistskuvalidation',
            table='picklist_sku_validation',
        ),
    ]
