version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    environment:
      - DB_NAME=orderprocess
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=False
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=orderprocess
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

volumes:
  postgres_data: